
library(R2jags)
library(RODBC)
library(reshape2)
library(plyr)
library(lattice)
library(RMark);cleanup(ask=FALSE)
library(sp)
library(rgdal)
library(maps)
library(maptools)
library(lubridate)
#library(date)
library(zoo)
